// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20231110161212_mos")]
    partial class mos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.21");

            modelBuilder.Entity("api.Models.FichaRpg", b =>
                {
                    b.Property<int>("IdFichaRpg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_ficha_rpg");

                    b.Property<string>("Alinhamento")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("alinhamento");

                    b.Property<string>("Antecedencia")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("antecedencia");

                    b.Property<DateTime?>("DataAtualizado")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_atualizado");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_criacao");

                    b.Property<bool?>("Deletado")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deletado");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_usuario");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nivel");

                    b.Property<string>("NomeDoJogador")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_do_jogador");

                    b.Property<int>("PontosDeExperiencia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pontos_de_experiencia");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("raca");

                    b.HasKey("IdFichaRpg")
                        .HasName("pk_fichas_rpg");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_fichas_rpg_id_usuario");

                    b.ToTable("fichas_rpg", (string)null);
                });

            modelBuilder.Entity("api.Models.Habilidade", b =>
                {
                    b.Property<int>("IdHabilidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_habilidade");

                    b.Property<int>("IdFichaRpg")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_ficha_rpg");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<int>("Pontos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pontos");

                    b.HasKey("IdHabilidade")
                        .HasName("pk_habilidades");

                    b.HasIndex("IdFichaRpg")
                        .HasDatabaseName("ix_habilidades_id_ficha_rpg");

                    b.ToTable("habilidades", (string)null);
                });

            modelBuilder.Entity("api.Models.Usuario", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_usuario");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_criacao");

                    b.Property<bool?>("Deletado")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deletado");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.HasKey("IdUsuario")
                        .HasName("pk_usuarios");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("api.Models.FichaRpg", b =>
                {
                    b.HasOne("api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fichas_rpg_usuarios_usuario_id_usuario");
                });

            modelBuilder.Entity("api.Models.Habilidade", b =>
                {
                    b.HasOne("api.Models.FichaRpg", null)
                        .WithMany()
                        .HasForeignKey("IdFichaRpg")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habilidades_fichas_rpg_ficha_rpg_id_ficha_rpg");
                });
#pragma warning restore 612, 618
        }
    }
}
